// Generated by CoffeeScript 1.8.0
var filename, folder, fs, generateConfig, glitchPath, path, pathInBrowser;

fs = require("fs");

path = require("path");

filename = "glitch.json";

pathInBrowser = "/images/glitch/";

glitchPath = "/public" + pathInBrowser;

folder = path.join(__dirname, glitchPath);

generateConfig = function() {
  var data, files;
  files = fs.readdirSync(folder);
  data = {
    'path': pathInBrowser,
    'images': files
  };
  data = JSON.stringify(data);
  fs.writeFileSync("public/" + filename, data);
  return data;
};

module.exports = generateConfig();
