// Generated by CoffeeScript 1.8.0
var nodemailer, options, transporter;

nodemailer = require('nodemailer');

transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.gmailAccount,
    pass: process.env.gmailPassword
  }
});

options = {
  from: "Rory Duncan <robust.rory@gmail.com>",
  to: "Test <robust.rory@gmail.com>",
  subject: "meow.coffee Contact Form Submission",
  text: "This is a test message"
};

transporter.sendMail(options, function(error, info) {
  if (error) {
    console.log("ERROR");
    console.log(error.code);
    return console.log(error.response);
  } else {
    return console.log(info.response);
  }
});
